server:
  address: 0.0.0.0
  port: 8080   # Gateway will run on port 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive   # Force reactive mode

  cloud:
    gateway:
      routes:

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/admin/product/** , /api/public/product/**

        - id: connection
          uri: lb://connection
          predicates:
            - Path=/api/public/connection/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/admin/user/** , /api/user/user/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/public/auth/** , /api/user/auth/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/admin/inventory/**

        - id: elasticsearch-service
          uri: lb://elasticsearch-service
          predicates:
            - Path=/api/public/search/** , api/admin/search/**

      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

