server:
  port: 8084

spring:
  application:
    name: inventory-service

  kafka:
    consumer:
      group-id: inventory-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.candlekart.inventory_service.dto.InventoryRequestList

  datasource:
    url: jdbc:postgresql://localhost:5432/candlekart
    username: akshayrathore
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always   # runs schema/data scripts at startup

eureka:
  instance:
    hostname: localhost



#  CREATE DATABASE candle_kart;
